var rule = {
  类型: '影视',
  title: '4K-AV',
  host: 'https://4k-av.com',
  url: '/fyclass/page-fypage.html[/fyclass/]',
  searchUrl: '/s?q=**&page=fypage',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'IOS_UA',
    
  },
  class_name: '电影&电视剧',
  class_url: 'movie&tv',
  timeout: 5000,
//  class_parse: '#cate_list&&li;a&&title;a&&href;/(\\w+)/',
 // cate_exclude: '成人视频',
  play_parse: true,
  lazy: "js:input = {parse: 1, url:input, js: '',header:rule.headers,}",
  double: true,
  推荐: '#recommlist;ul&&li;h2&&Text;img&&src;span&&Text;a&&href',
  一级: '#MainContent_newestlist&&.NTMitem;h2&&Text;img&&src;div.resyear&&Text;a&&href',
  二级: {
    title: 'h2&&Text;#MainContent_tags&&Text',
    img: 'img&&src',
    desc: '#MainContent_videodetail&&label&&Text;#MainContent_videodetail&&label:eq(2)&&Text;;;',
    content: '',
    tabs: '',
    lists: '#rtlist&&a',
    list_url: 'a&&href',
    list_text: 'span&&Text',
    tab_text: '4K-AV',
  },
  搜索: '*',
}